//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StroyTehNadzor.PageControls {
    
    public partial class News {
        protected System.Web.UI.WebControls.Literal lNews;
    }
}
