//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stroytehnadzor {
    
    
    public partial class Flaw1 {
        
        /// <summary>
        /// PostMessageControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::stroytehnadzor.PageControls.PostMessage PostMessageControl;
        
        /// <summary>
        /// AnswersControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::stroytehnadzor.PageControls.Answers AnswersControl;
    }
}
